spark.plugins=org.apache.gluten.GlutenPlugin
spark.memory.offHeap.enabled=true
spark.memory.offHeap.size=2g

spark.plugins=org.apache.gluten.GlutenPlugin

spark.jars=/opt/gluten/gluten-velox-bundle-spark3.5_2.12-linux_amd64-1.6.0.jar

spark.driver.extraClassPath=/opt/gluten/gluten-velox-bundle-spark3.5_2.12-linux_amd64-1.6.0.jar
spark.executor.extraClassPath=/opt/gluten/gluten-velox-bundle-spark3.5_2.12-linux_amd64-1.6.0.jar